package main

import (
	"fmt"
	"log"
	"os/exec"
	"time"
)

func main() {
	// Calculate the next full hour.
	now := time.Now()
	nextHour := now.Truncate(time.Hour).Add(time.Hour)
	startTime := nextHour.Format("15:04") // Format as HH:MM (24-hour)

	// Define the scheduled task parameters.
	taskName := "PersephoneBackupHourly"
	// Use cmd.exe to run the batch file generated by the other Delphi scripts.
	// Adjust the path if needed.
	taskAction := `cmd.exe /c "C:\opt\persephone\windows\persephone.bat"`

	// Build the schtasks command.
	cmd := exec.Command("schtasks",
		"/create",
		"/tn", taskName,
		"/tr", taskAction,
		"/sc", "hourly",
		"/ST", startTime,
	)

	// Execute the command.
	output, err := cmd.CombinedOutput()
	if err != nil {
		log.Fatalf("Failed to create scheduled task: %v\nOutput: %s", err, string(output))
	}

	fmt.Printf("Scheduled task '%s' created successfully. Output:\n%s", taskName, string(output))
}
