---
- name: Run Persephone Restic Backup with Vault Secrets
  hosts: all
  become: yes
  vars_files:
    - persephone-vault-enc.yml
  tasks:
    - name: Display backup directories (for testing)
      debug:
        msg: "Backing up directories: {{ backup_dirs }}"

    - name: Run Persephone Restic backup
      command: >
        restic -r {{ restic_url }}
        --password-file {{ restic_password_file }}
        --verbose
        --tag "{{ restic_tag }}"
        backup {{ backup_dirs | join(' ') }}
      environment:
        AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
        AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
