---
- name: Initialize Restic Repository with Vault Secrets
  hosts: all
  become: yes
  vars_files:
    - persephone-vault.yml.template
  tasks:
    - name: Initialize the Restic repository
      command: >
        restic init -r {{ restic_url }}
        --password-file {{ restic_password_file }}
      environment:
        AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
        AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
