---
- name: Remove restic backup lines from root crontabs
  hosts: all
  become: yes
  vars:
    crontab_user: root
    backup_dir: /root/ansible_cron_backups
  tasks:

    - name: Ensure backup directory exists
      file:
        path: "{{ backup_dir }}"
        state: directory
        mode: '0700'

    - name: Backup current crontab for user {{ crontab_user }}
      shell: "crontab -l -u {{ crontab_user }} || true"
      register: current_crontab

    - name: Save current crontab to backup file
      copy:
        content: "{{ current_crontab.stdout }}"
        dest: "{{ backup_dir }}/{{ crontab_user }}_crontab_{{ ansible_date_time.iso8601_basic }}.bak"
      when: current_crontab.stdout != ""

    - name: Remove lines containing 'restic' from crontab for user {{ crontab_user }}
      shell: "crontab -l -u {{ crontab_user }} 2>/dev/null | grep -v 'restic' | crontab -u {{ crontab_user }} -"

      register: update_crontab
      changed_when: update_crontab.rc == 0

    - name: Inform that crontab has been updated
      debug:
        msg: "Crontab for user {{ crontab_user }} updated successfully."
