---
- name: Schedule Persephone S3 Backup via Cron on Endpoints
  hosts: all
  become: yes
  vars_files:
    - persephone-vault-enc.yml

  tasks:
    - name: Generate random backup time
      set_fact:
        backup_minute: "{{ range(0, 60) | random }}"
        backup_hour: "{{ range(0, 24) | random }}"

    - name: Install Persephone S3 backup cron job
      cron:
        name: "Persephone S3 Backup"
        minute: "{{ backup_minute }}"
        hour: "{{ backup_hour }}"
        # The job sets the AWS credentials as environment variables inline,
        # then runs the restic backup command using the repository URL, password file, and backup directories.
        job: >
          AWS_ACCESS_KEY_ID={{ aws_access_key_id }} AWS_SECRET_ACCESS_KEY={{ aws_secret_access_key }} 
          restic -r {{ restic_url }} --password-file {{ restic_password_file }} backup {{ backup_dirs | join(' ') }}
          --tag "{{ inventory_hostname }}-$(date +\\%Y-\\%m-\\%d_\\%H-\\%M-\\%S)"
        user: root
