# updatePersephoneToHourly.yml
---
- name: Update all restic-related cron jobs to run hourly
  hosts: all
  become: yes
  vars:
    tmp_cron_file: /tmp/new_crontab
  tasks:
    - name: Retrieve current crontab
      shell: crontab -l || true
      register: current_crontab
      changed_when: false

    - name: Build new crontab content with updated hour field
      set_fact:
        new_crontab: |
          {% for line in current_crontab.stdout_lines %}
          {% if 'restic' in line | lower %}
          {{ line | regex_replace('^(\S+)\s+\S+(.*)$', '\\1 *\\2') }}
          {% else %}
          {{ line }}
          {% endif %}
          {% if not loop.last %} 
          {% endif %}
          {% endfor %}

    - name: Write new crontab to temporary file
      copy:
        content: "{{ new_crontab }}"
        dest: "{{ tmp_cron_file }}"
        mode: '0644'

    - name: Install updated crontab
      command: crontab "{{ tmp_cron_file }}"
